import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useStorefront } from '../../../../shared/generalContext.jsx';
import api from '../../../../shared/services/api';
import { validateCpfOrCnpj } from '../../../../shared/utils/validators';

// Fluxo de primeiro acesso para telas pequenas (<768px). O tour ancorado
// (FirstAccessWizard) quebra no mobile — o card de dica cobre os campos. Aqui
// mostramos uma única tela cheia com os dados essenciais da loja (nome, link e
// CPF/CNPJ), obrigatórios, com botão "Continuar". Ao concluir, delega para
// onComplete({ oldSlug, newSlug }) — que marca o wizard como concluído e trata a
// eventual troca de slug (recarregando na nova URL).

const RESERVED_SLUGS = ['app', 'dashboard', 'onboarding', 'login', 'admin', 'api', 'tenant', 'tenants', 'orders', 'menu', 'settings'];

const normalizeSlug = (raw) =>
  String(raw || '')
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-+/, '');

const validateSlug = (s) => {
  if (!s) return 'Informe o link da sua loja.';
  if (s.length < 3 || s.length > 30) return 'O link deve ter entre 3 e 30 caracteres.';
  if (!/^[a-z][a-z0-9-]*$/.test(s)) return 'Use letras minúsculas, números e hífen, começando por uma letra.';
  if (/-{2,}/.test(s)) return 'Evite hífens consecutivos.';
  if (s.endsWith('-')) return 'Não termine com hífen.';
  if (RESERVED_SLUGS.includes(s)) return 'Este link é reservado. Escolha outro.';
  return '';
};

const looksAutoGenerated = (slug) => /^minha-loja-/.test(String(slug || ''));

const MobileFirstAccessForm = ({ active, onComplete }) => {
  const { tenant, updateTenant } = useStorefront();

  const [name, setName] = useState('');
  const [slug, setSlug] = useState('');
  const [doc, setDoc] = useState('');
  const [slugCheck, setSlugCheck] = useState({ slug: '', status: 'idle' });
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');
  const seededRef = useRef(false);

  const currentSlug = String(tenant?.slug || '');

  // Prefill uma única vez, a partir do tenant carregado.
  useEffect(() => {
    if (seededRef.current || !tenant) return;
    seededRef.current = true;
    const n = String(tenant?.name || '').trim();
    setName(n && n.toLowerCase() !== 'minha loja' ? n : '');
    setSlug(currentSlug && !looksAutoGenerated(currentSlug) ? currentSlug : '');
    setDoc(String(tenant?.cnpj_cpf || ''));
  }, [tenant, currentSlug]);

  const storeOrigin = typeof window !== 'undefined' ? window.location.origin : '';

  // Checagem de disponibilidade do slug (debounce), espelhando o Settings.
  useEffect(() => {
    if (!active) return undefined;
    const value = normalizeSlug(slug);
    if (validateSlug(value)) {
      setSlugCheck({ slug: value, status: 'invalid' });
      return undefined;
    }
    // O próprio slug atual da loja conta como disponível.
    if (currentSlug && value === currentSlug) {
      setSlugCheck({ slug: value, status: 'available' });
      return undefined;
    }
    let cancelled = false;
    setSlugCheck({ slug: value, status: 'checking' });
    const id = window.setTimeout(async () => {
      try {
        const result = await api.get(`/onboarding/slug-available?slug=${encodeURIComponent(value)}`).catch(() => null);
        if (cancelled) return;
        const available = !result || result.available !== false;
        setSlugCheck({ slug: value, status: available ? 'available' : 'taken' });
      } catch (_) {
        if (!cancelled) setSlugCheck({ slug: value, status: 'available' });
      }
    }, 400);
    return () => {
      cancelled = true;
      window.clearTimeout(id);
    };
  }, [slug, active, currentSlug]);

  const normalizedSlug = normalizeSlug(slug);
  const nameOk = name.trim().length > 0 && name.trim().toLowerCase() !== 'minha loja';
  const docOk = doc.trim().length > 0 && validateCpfOrCnpj(doc.trim()) === '';
  const slugFormatError = validateSlug(normalizedSlug);
  const slugStatus = slugCheck.slug === normalizedSlug ? slugCheck.status : 'idle';
  const slugOk = !slugFormatError && (slugStatus === 'available' || normalizedSlug === currentSlug);

  const canSubmit = nameOk && docOk && slugOk && !submitting;

  const docHint = useMemo(() => {
    const v = doc.trim();
    if (!v) return '';
    return validateCpfOrCnpj(v);
  }, [doc]);

  const slugHint = (() => {
    if (!normalizedSlug) return '';
    if (slugFormatError) return slugFormatError;
    if (slugStatus === 'checking') return 'Verificando disponibilidade…';
    if (slugStatus === 'taken') return 'Esse link já está em uso. Escolha outro.';
    if (slugStatus === 'available') return 'Link disponível!';
    return '';
  })();

  const handleSubmit = async (e) => {
    e?.preventDefault?.();
    if (!canSubmit) return;
    setError('');
    setSubmitting(true);
    const oldSlug = currentSlug;
    const newSlug = normalizedSlug;
    try {
      const success = await updateTenant({
        name: name.trim(),
        slug: newSlug,
        cnpj_cpf: doc.trim(),
      });
      if (!success) {
        setError('Não foi possível salvar. Tente novamente.');
        setSubmitting(false);
        return;
      }
      onComplete?.({ oldSlug, newSlug });
    } catch (_) {
      setError('Não foi possível salvar. Tente novamente.');
      setSubmitting(false);
    }
  };

  if (!active) return null;

  const inputBase =
    'w-full rounded-2xl border px-4 py-3.5 text-base text-gray-900 outline-none transition-colors placeholder:text-gray-400 focus:border-[var(--accent)]';

  return (
    <div className="fixed inset-0 z-[80] overflow-y-auto bg-white">
      <div className="mx-auto flex min-h-full w-full max-w-md flex-col px-5 pb-10 pt-8">
        <div className="mb-6">
          <span
            className="inline-flex rounded-full px-3 py-1 text-xs font-semibold uppercase tracking-wide"
            style={{ background: 'color-mix(in srgb, var(--accent) 12%, white)', color: 'var(--accent)' }}
          >
            Primeiros passos
          </span>
          <h1 className="mt-4 text-2xl font-extrabold leading-tight text-gray-900">
            Vamos configurar sua loja
          </h1>
          <p className="mt-2 text-sm leading-6 text-gray-500">
            Preencha os dados essenciais para colocar seu restaurante no ar. Você ajusta o resto
            depois, com calma, no painel.
          </p>
        </div>

        <form onSubmit={handleSubmit} className="flex flex-1 flex-col gap-5">
          {/* Nome */}
          <div>
            <label className="mb-1.5 block text-sm font-semibold text-gray-800">
              Nome do restaurante
            </label>
            <input
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="Ex.: Pizzaria do Pedro"
              className={inputBase}
              style={{ borderColor: name && !nameOk ? '#f87171' : '#e5e7eb' }}
              autoComplete="organization"
            />
            {name && !nameOk && (
              <p className="mt-1.5 text-xs text-red-500">Escolha um nome (diferente de “Minha Loja”).</p>
            )}
          </div>

          {/* Link / slug */}
          <div>
            <label className="mb-1.5 block text-sm font-semibold text-gray-800">
              Link da sua loja
            </label>
            <input
              type="text"
              value={slug}
              onChange={(e) => setSlug(normalizeSlug(e.target.value))}
              placeholder="pizzaria-do-pedro"
              inputMode="url"
              autoCapitalize="none"
              autoCorrect="off"
              spellCheck={false}
              className={inputBase}
              style={{
                borderColor: normalizedSlug
                  ? (slugOk ? '#34d399' : (slugStatus === 'checking' ? '#e5e7eb' : '#f87171'))
                  : '#e5e7eb',
              }}
            />
            <p className="mt-1.5 break-all text-xs text-gray-400">
              {storeOrigin}/<span className="font-semibold text-gray-600">{normalizedSlug || 'seu-link'}</span>
            </p>
            {slugHint && (
              <p
                className="mt-1 text-xs"
                style={{ color: slugStatus === 'available' ? '#059669' : (slugStatus === 'checking' ? '#6b7280' : '#ef4444') }}
              >
                {slugHint}
              </p>
            )}
          </div>

          {/* CPF/CNPJ */}
          <div>
            <label className="mb-1.5 block text-sm font-semibold text-gray-800">
              CPF ou CNPJ
            </label>
            <input
              type="text"
              value={doc}
              onChange={(e) => setDoc(e.target.value)}
              placeholder="Somente números"
              inputMode="numeric"
              className={inputBase}
              style={{ borderColor: doc && !docOk ? '#f87171' : '#e5e7eb' }}
            />
            {doc && docHint && (
              <p className="mt-1.5 text-xs text-red-500">{docHint}</p>
            )}
          </div>

          {error && (
            <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-600">
              {error}
            </div>
          )}

          <div className="mt-auto pt-4">
            <button
              type="submit"
              disabled={!canSubmit}
              className="w-full rounded-2xl px-5 py-4 text-base font-bold transition-all disabled:cursor-not-allowed disabled:opacity-40"
              style={{ background: 'var(--accent)', color: 'var(--accent-contrast)' }}
            >
              {submitting ? 'Salvando…' : 'Continuar'}
            </button>
            <p className="mt-3 text-center text-[11px] leading-snug text-gray-400">
              Esses dados são obrigatórios para sua loja funcionar e receber pedidos.
            </p>
          </div>
        </form>
      </div>
    </div>
  );
};

export default MobileFirstAccessForm;
